services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: your_pg_user
      POSTGRES_PASSWORD: your_pg_password
      POSTGRES_DB: your_db_name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.8.2-python3.10
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://your_pg_user:your_pg_password@postgres:5432/your_db_name
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/requirements.txt
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    command: >
      bash -c "
        pip install -r /requirements.txt &&
        airflow db migrate &&
        airflow users create --username admin --firstname Harshit --lastname Raj --role Admin --email iamrajharshit@gmail.com --password @Cenarocks388 &&
        airflow webserver
      "

  scheduler:
    image: apache/airflow:2.8.2-python3.10
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://your_pg_user:your_pg_password@postgres:5432/your_db_name
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/requirements.txt
    depends_on:
      - airflow
      - postgres
    command: >
      bash -c "
        pip install -r /requirements.txt &&
        airflow scheduler
      "

volumes:
  postgres_data:
